# Generated by Django 2.1.1 on 2019-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarybill',
            name='total_all_salary',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
