# Generated by Django 2.1.1 on 2019-02-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190225_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarybill',
            name='total_all_salary',
        ),
        migrations.AddField(
            model_name='salarybill',
            name='total_sal',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
    ]
